-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 08:10:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BIBLIOTECA_MODEL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BIBLIOTECA_MODEL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BIBLIOTECA_MODEL` DEFAULT CHARACTER SET utf8 ;
USE `BIBLIOTECA_MODEL` ;

-- -----------------------------------------------------
-- Table `BIBLIOTECA_MODEL`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA_MODEL`.`autores` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BIBLIOTECA_MODEL`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA_MODEL`.`categorias` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BIBLIOTECA_MODEL`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA_MODEL`.`livros` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `ano_publicacao` INT NULL,
  `id_categoria` INT NOT NULL,
  `id_autor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_autor_idx` (`id_autor` ASC) VISIBLE,
  INDEX `id_categorias_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `id_autor`
    FOREIGN KEY (`id_autor`)
    REFERENCES `BIBLIOTECA_MODEL`.`autores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_categorias`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `BIBLIOTECA_MODEL`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BIBLIOTECA_MODEL`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA_MODEL`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `endereco` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BIBLIOTECA_MODEL`.`emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BIBLIOTECA_MODEL`.`emprestimos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NULL,
  `id_livro` INT NULL,
  `data_retirada` DATE NULL,
  `data_devolucao` DATE NULL,
  `status` ENUM('Em andamento', 'Concluído') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `id_livro_idx` (`id_livro` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `BIBLIOTECA_MODEL`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_livro`
    FOREIGN KEY (`id_livro`)
    REFERENCES `BIBLIOTECA_MODEL`.`livros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
