-- MySQL Script generated by MySQL Workbench
-- Tue Apr  8 11:08:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema HOTEL_MODEL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HOTEL_MODEL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HOTEL_MODEL` DEFAULT CHARACTER SET utf8 ;
USE `HOTEL_MODEL` ;

-- -----------------------------------------------------
-- Table `HOTEL_MODEL`.`hospedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HOTEL_MODEL`.`hospedes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HOTEL_MODEL`.`quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HOTEL_MODEL`.`quartos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(20) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `preco_diaria` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HOTEL_MODEL`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HOTEL_MODEL`.`reservas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_hospede` INT NOT NULL,
  `data_checkin` DATE NOT NULL,
  `data_checkout` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_hospedes_idx` (`id_hospede` ASC) VISIBLE,
  CONSTRAINT `id_hospedes`
    FOREIGN KEY (`id_hospede`)
    REFERENCES `HOTEL_MODEL`.`hospedes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HOTEL_MODEL`.`quartos_reservados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HOTEL_MODEL`.`quartos_reservados` (
  `id_reserva` INT NOT NULL,
  `id_quarto` INT NOT NULL,
  INDEX `id_reserva_idx` (`id_reserva` ASC) VISIBLE,
  INDEX `id_quarto_idx` (`id_quarto` ASC) VISIBLE,
  CONSTRAINT `id_reserva`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `HOTEL_MODEL`.`reservas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id_quarto`
    FOREIGN KEY (`id_quarto`)
    REFERENCES `HOTEL_MODEL`.`quartos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HOTEL_MODEL`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HOTEL_MODEL`.`pagamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_reserva` INT NULL,
  `valor` DECIMAL(10,2) NULL,
  `metodo_pagamento` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_reservas_idx` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `id_reservas`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `HOTEL_MODEL`.`reservas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HOTEL_MODEL`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HOTEL_MODEL`.`telefone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(20) NOT NULL,
  `id_hospede` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  INDEX `id_hospedes_idx` (`id_hospede` ASC) VISIBLE,
  CONSTRAINT `id_hospede`
    FOREIGN KEY (`id_hospede`)
    REFERENCES `HOTEL_MODEL`.`hospedes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
